### PR TITLE
Update deps APIs

### PR DESCRIPTION
**Pull request by JasonEtco**
Update the APIs of `add-collabs` and `remind-merge` to use the new setup with `configurable`. Add the `defaults` object and the config filename as arguments to both of those functions.

### CODE REVIEW

**Comment by hectorsector** [comment]
@JasonEtco I removed the filename parameter from this PR, https://github.com/teacher-bot/add-collabs/pull/2, and https://github.com/teacher-bot/remind-merge/pull/3, so I could do some testing across the 3 plugins, but feel free to add it back in if you think it's beneficial.

**Comment by JasonEtco** [comment]
@hectorsector - I'm fine with hard-coding the config filename into `add-collabs` and `remind-merge`, but it means that those two "plugins" can only be used within teacherbot. If I wanted to build my own bot called Jasonbot and wanted to use that code, I would have to include a `teacherbot.yml` config file.

If we decidedly don't want to be able to reuse these plugins outside of teacherbot, that is a-okay, but generally I think reusability is cool 👍

**Comment by hectorsector** [comment]
@JasonEtco very good point, I added the option for that param back in on 2c459cf, which necessitated some updates to https://github.com/teacher-bot/add-collabs/pull/3/commits/7d33b145fb2240bac58cac679ff7b0533b40a6a1 and https://github.com/teacher-bot/remind-merge/pull/3/commits/ad76e49f4cc462aac6e83cc660fdd701e3ca91de.

I think this is ready to ship if I can get at least one set of 👀. Heads up... to properly test this you can change the `package.json` file locally so it points to the open branches on the other two repos like such:

```json
  "dependencies": {
    "add-collabs": "teacher-bot/add-collabs#use-probot-config",
    "probot": "^0.8.0",
    "remind-merge": "teacher-bot/remind-merge#use-probot-config"
  },
```

Then remove your `node_modules` folder and run `npm install`.

**Comment by JasonEtco** [comment]
@hectorsector I think we still have some work to do 🎉 

Based on the JSDoc comments that I've written, `add-collabs` is looking for an object that contains two keys, `existingCollaboratorMessage` and `newCollaboratorMessage`. What we're sending it now is an object containing the defaults for both `add-collabs` and `remind-merge`, which is unnecessary. I suggest that we define some defaults in `index.js` then send only the object relevant to `add-collabs`, so we do:

```js
const defaults = {
  addCollaborators: {
    newCollaboratorMessage: 'Hi! I\'m the friendly :robot: of this repo.\n\nWe\'re happy you\'re here :wave:. Everyone is welcome here, so I\'m making you a collaborator. This will give you access to commit on this repo.',
    existingCollaboratorMessage: 'Hi! I\'m the friendly :robot: of this repo.\n\nI can see that you\'re already a collaborator. Any other issues are above my paygrade at the moment, so we\'ll have to wait for a pesky hu-man. Not to worry though, they\'ll drop by within 24 hours to answer your questions!'
  },
  remindMerge: {
    message: ':wave: hiya Please remember to delete your branch after merging or closing if you haven\'t done so already.'
  }
};

module.exports = async robot => {
  addCollabs(robot, defaults.addCollaborators, 'teacherbot.yml');
  remindMerge(robot, defaults.remindMerge, 'teacherbot.yml');
};
```

Also, we're defining 2 "defaults": one for teacherbot, and one for `add-collabs`. What if we removed the defaults in `add-collabs`, and had it throw an error if there are default config things missing (that should be passed by teacherbot)? This would make sure that we're not repeating default settings, and that we make it clear what information `add-collabs` needs to have to operate.

<sub>Anytime I say `add-collabs` it applies to `remind-merge` as well</sub>

Edit: I've realized that some of those changes should be made in the individual repos, so for this PR it's really just a question of what we pass to the modules

**Comment by hectorsector** [comment]
@JasonEtco I'm getting the error below.

```bash
20:56:47.993Z DEBUG PRobot: Loaded plugin: ./index.js
20:56:47.996Z TRACE PRobot: Listening on http://localhost:3000
20:56:48.007Z ERROR PRobot:
  Promise {
    <rejected> ReferenceError: defaults is not defined
      at Object.keys.filter.key (/Users/halfaro1/teacherbot/teacherbot/node_modules/add-collabs/index.js:7:97)
      at Array.filter (native)
      at checkForDefaults (/Users/halfaro1/teacherbot/teacherbot/node_modules/add-collabs/index.js:7:45)
      at module.exports (/Users/halfaro1/teacherbot/teacherbot/node_modules/add-collabs/index.js:22:3)
      at module.exports (/Users/halfaro1/teacherbot/teacherbot/index.js:15:3)
      at Object.load (/Users/halfaro1/teacherbot/teacherbot/node_modules/probot/index.js:69:7)
      at loadPlugin (/Users/halfaro1/teacherbot/teacherbot/node_modules/probot/lib/plugin.js:36:14)
      at pluginNames.forEach.pluginName (/Users/halfaro1/teacherbot/teacherbot/node_modules/probot/lib/plugin.js:63:7)
      at Array.forEach (native)
      at Object.load (/Users/halfaro1/teacherbot/teacherbot/node_modules/probot/lib/plugin.js:61:17)
      at pkgConf.then.pkg (/Users/halfaro1/teacherbot/teacherbot/node_modules/probot/bin/probot-run.js:66:13) }
  --
  ReferenceError: defaults is not defined
      at Object.keys.filter.key (/Users/halfaro1/teacherbot/teacherbot/node_modules/add-collabs/index.js:7:97)
      at Array.filter (native)
      at checkForDefaults (/Users/halfaro1/teacherbot/teacherbot/node_modules/add-collabs/index.js:7:45)
      at module.exports (/Users/halfaro1/teacherbot/teacherbot/node_modules/add-collabs/index.js:22:3)
      at module.exports (/Users/halfaro1/teacherbot/teacherbot/index.js:15:3)
      at Object.load (/Users/halfaro1/teacherbot/teacherbot/node_modules/probot/index.js:69:7)
      at loadPlugin (/Users/halfaro1/teacherbot/teacherbot/node_modules/probot/lib/plugin.js:36:14)
      at pluginNames.forEach.pluginName (/Users/halfaro1/teacherbot/teacherbot/node_modules/probot/lib/plugin.js:63:7)
      at Array.forEach (native)
      at Object.load (/Users/halfaro1/teacherbot/teacherbot/node_modules/probot/lib/plugin.js:61:17)
      at pkgConf.then.pkg (/Users/halfaro1/teacherbot/teacherbot/node_modules/probot/bin/probot-run.js:66:13)
```

**Comment by hectorsector** [comment]
@teacher-bot/training-team this branch is currently deployed to the staging server, which is being used by [`teacherbot-staging`](https://github.com/organizations/githubschool/settings/apps/teacherbot-staging). It can be tested by interacting with a repo in which it's already installed (like [happy-day](https://github.com/githubschool/happy-day)), or by [installing it](https://github.com/apps/teacherbot-staging) on a repo of your choice. 

Things to test:
- response to a new issue when someone's not a collab
- response to a new issue when someone is a collab
- response to a PR being merged
- response to a PR being closed
- adding a `.github/teacherbot.yml` file [with configs](https://github.com/githubschool/happy-day/blob/master/.github/teacherbot.yml) and seeing those responses being used, instead

**Comment by brianamarie** [comment]
@hectorsector, you couldn't have made it any easier to test. I've tested all of the things you outlined above, and they worked perfectly!!! I say 🚢 

### Testing on [happy-day](https://github.com/githubschool/happy-day)

- [x] [response to a new issue when someone's not a collab](https://github.com/githubschool/happy-day/issues/74)
- [x] [response to a new issue when someone is a collab](https://github.com/githubschool/happy-day/issues/75)
- [x] [response to a PR being merged](https://github.com/githubschool/happy-day/pull/76)
- [x] [response to a PR being closed](https://github.com/githubschool/happy-day/pull/77)
- [x] [adding a .github/teacherbot.yml file with configs and seeing those responses being used, instead](https://github.com/githubschool/happy-day/blob/master/.github/teacherbot.yml)

### Testing on [a new repo](https://github.com/brianamarie/feb-recipes)

- [x] [response to a new issue when someone's not a collab](https://github.com/brianamarie/feb-recipes/issues/1)
- [x] [response to a new issue when someone is a collab](https://github.com/brianamarie/feb-recipes/issues/2)
- [x] [response to a PR being merged](https://github.com/brianamarie/feb-recipes/pull/3)
- [x] [response to a PR being closed](https://github.com/brianamarie/feb-recipes/pull/3)
- [x] [adding a .github/teacherbot.yml file with configs and seeing those responses being used, instead](https://github.com/brianamarie/feb-recipes/issues/4)

**Comment by crichID** [comment]
## Testing on [a new repo](https://github.com/crichID/arduino-garden-tender)

- [x] [response to a new issue when someone's not a collab](https://github.com/crichID/arduino-garden-tender/issues/3)
- [x] [response to a new issue when someone is a collab](https://github.com/crichID/arduino-garden-tender/issues/4)
- [x] [response to a PR being merged](https://github.com/crichID/arduino-garden-tender/pull/5#issuecomment-319745445)
- [x] [response to a PR being closed](https://github.com/crichID/arduino-garden-tender/pull/5#issuecomment-319745249)
- [x] [adding a .github/teacherbot.yml file with configs and seeing those responses being used, instead](https://github.com/crichID/arduino-garden-tender/blob/master/.github/teacherbot.yml)

@hectorsector everything tests perfectly. I do have one question we can look at after this ship:

- For the remindMerge, could we have it show a different message when they close the PR instead of merging it. For example, could we say something like "hey, I noticed you just closed your PR instead of merging it. If you do that, your changes will not appear in production. If you want your changes in production, please re-open this pull request and click the green 'Merge Pull Request' button instead."

**Comment by hectorsector** [comment]
> For the remindMerge, could we have it show a different message when they close the PR instead of merging it.

I think that's definitely doable, @crichID, but I'd open a new issue for it in [remind-merge](https://github.com/teacher-bot/remind-merge) itself.

**Comment by hectorsector** [comment]
I noticed that the default responses @brianamarie  was getting were "heya" and "delete!" which are the responses that were customized back in [happy-day](https://github.com/githubschool/happy-day/blob/master/.github/teacherbot.yml). Then I noticed that @crichID was getting some of the responses that @brianamarie was setting...

Soooo I'm thinking that's something buggy. It appears the last used config is being cached, rather than using the defaults.

**Pull request merged**
