### PR TITLE
Add scripts to rule them all

### PR DESCRIPTION
**Pull request by hectorsector**
This PR adds the [Scripts to Rule Them All](https://github.com/github/scripts-to-rule-them-all/) to this repo. This is necessary as we begin to ramp up development and to support our staging and deployment needs.

### CODE REVIEW

**Comment by hectorsector** [comment]
@crichID this is relevant to #4

**Comment by hectorsector** [comment]
@teacher-bot/training-team could I get some 👍 so I can 🚢 this?

**Comment by brianamarie** [comment]
@hectorsector 👋 I tried testing these locally, but when I ran `script/bootstrap`, I ran into the following errors: 

```
➜  teacherbot (scripts-to-rule-all) script/bootstrap 
npm ERR! git fetch -a origin (git://github.com/teacher-bot/configurable.git) fatal: remote error: 
npm ERR! git fetch -a origin (git://github.com/teacher-bot/configurable.git)   Repository not found.
npm ERR! git clone --template=/Users/brianamarie/.npm/_git-remotes/_templates --mirror git@github.com:teacher-bot/configurable.git /Users/brianamarie/.npm/_git-remotes/git-github-com-teacher-bot-configurable-git-c1ffa35c: Cloning into bare repository '/Users/brianamarie/.npm/_git-remotes/git-github-com-teacher-bot-configurable-git-c1ffa35c'...
npm ERR! git clone --template=/Users/brianamarie/.npm/_git-remotes/_templates --mirror git@github.com:teacher-bot/configurable.git /Users/brianamarie/.npm/_git-remotes/git-github-com-teacher-bot-configurable-git-c1ffa35c: ERROR: Repository not found.
npm ERR! git clone --template=/Users/brianamarie/.npm/_git-remotes/_templates --mirror git@github.com:teacher-bot/configurable.git /Users/brianamarie/.npm/_git-remotes/git-github-com-teacher-bot-configurable-git-c1ffa35c: fatal: Could not read from remote repository.
npm ERR! git clone --template=/Users/brianamarie/.npm/_git-remotes/_templates --mirror git@github.com:teacher-bot/configurable.git /Users/brianamarie/.npm/_git-remotes/git-github-com-teacher-bot-configurable-git-c1ffa35c: 
npm ERR! git clone --template=/Users/brianamarie/.npm/_git-remotes/_templates --mirror git@github.com:teacher-bot/configurable.git /Users/brianamarie/.npm/_git-remotes/git-github-com-teacher-bot-configurable-git-c1ffa35c: Please make sure you have the correct access rights
npm ERR! git clone --template=/Users/brianamarie/.npm/_git-remotes/_templates --mirror git@github.com:teacher-bot/configurable.git /Users/brianamarie/.npm/_git-remotes/git-github-com-teacher-bot-configurable-git-c1ffa35c: and the repository exists.
npm ERR! Darwin 16.6.0
npm ERR! argv "/Users/brianamarie/.nvm/versions/node/v7.10.0/bin/node" "/Users/brianamarie/.nvm/versions/node/v7.10.0/bin/npm" "install"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code 128

npm ERR! Command failed: git clone --template=/Users/brianamarie/.npm/_git-remotes/_templates --mirror git@github.com:teacher-bot/configurable.git /Users/brianamarie/.npm/_git-remotes/git-github-com-teacher-bot-configurable-git-c1ffa35c
npm ERR! Cloning into bare repository '/Users/brianamarie/.npm/_git-remotes/git-github-com-teacher-bot-configurable-git-c1ffa35c'...
npm ERR! ERROR: Repository not found.
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/brianamarie/.npm/_logs/2017-08-01T13_43_12_830Z-debug.log
```

Do you know how I should get access to initial repositories? Are they all on GitHub, or are some of them the Heroku remotes?

**Comment by hectorsector** [comment]
Thanks for testing, @brianamarie! we got rid of the `configurable` dependency in #2 (specifically [here](https://github.com/teacher-bot/teacherbot/pull/2/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L14)). Might want to merge that in to test it.

**Comment by JasonEtco** [comment]
@hectorsector I think this is an error in `add-collabs` and `remind-merge` (they are both looking for configurable)

**Comment by hectorsector** [comment]
> I think this is an error in add-collabs and remind-merge (they are both looking for configurable)

👍 right, and [here's](https://github.com/teacher-bot/teacherbot/pull/2#issuecomment-319145978) some instructions on how to test the branches without that dependency.

**Pull request merged**
