### PR TITLE
Specify node version

### PR DESCRIPTION
**Pull request by hectorsector**
This PR specifies the node version which is needed for a Heroku deployment.

### CODE REVIEW

**Comment by hectorsector** [comment]
Through this PR I've also been able to deploy to a staging server. The [staging server](https://floating-hollows-41486.herokuapp.com/) is now connected to the [`teacherbot-staging`](https://github.com/organizations/githubschool/settings/apps/teacherbot-staging) app. That means that you can try it on any repository that app is installed in, like [this one](https://github.com/githubschool/local-teacherbot). 
 
@JasonEtco @teacher-bot/training-team can I get some 👀 on this PR? If it looks good I'll merge it which will automatically move it into production.

**Comment by JasonEtco** [comment]
@hectorsector yay! Since Probot now has a `configurable` equivalent [as of `0.8.0`](https://github.com/probot/probot/blob/master/CHANGELOG.md#080-2017-07-27), do we want to make that change in a separate PR? Or should we adjust this PR?

**Comment by hectorsector** [comment]
Yes! Let's start a new PR for that.

**Comment by JasonEtco** [comment]
Cool - in that case, LGTM 🚢

**Pull request merged**
